# Generated by Django 5.1.4 on 2025-01-23 06:25

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_book_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=notes.models.upload_to),
        ),
    ]
