# Generated by Django 5.1.4 on 2025-01-07 06:25

import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(default=notes.models.generate_isbn),
        ),
    ]
